### ISSUE TITLE
Allow preserving of last modification time

### ISSUE THREAD

**Issue by Gregvh** [cryptomator/cryptofs#33]
See https://github.com/cryptomator/cryptomator/issues/220
I have done some tests with FUSE, the following methods are called during "cp -p" :
1. OpenCryptoFile.write to copy the file data
2. AbstractCryptoFileAttributeView.setTimes to copy the last access and modification times
3. OpenCryptoFile.force to flush all data to disk
During this third step we call this:
https://github.com/cryptomator/cryptofs/blob/77a17a0a8896a19164f81e28fc4bdde13fa20fd3/src/main/java/org/cryptomator/cryptofs/OpenCryptoFile.java#L160
This leads to the ChuckSaver.save being called and finally this write:
https://github.com/cryptomator/cryptofs/blob/77a17a0a8896a19164f81e28fc4bdde13fa20fd3/src/main/java/org/cryptomator/cryptofs/ChunkSaver.java#L40
This write updates the last modification time to "now", meaning the one we copied during step 2 is lost.

**Comment by infeo** [comment]
Mhm, i would suggest a more general approach and not only when `setTimes()` is explicitly called.

The reason is that some programs relay on the timestamp and when it changes they think the file is modified (i.e. i think also issue [cryptomator/cryptomator/#705](https://github.com/cryptomator/cryptomator/issues/705) of is affected by this).

Maybe after each force we write the correct mTime? Of course this affects performances (for each `force()`-call we get two filesystem calls), but it would at least prevent a wrong last modified date

**Comment by overheadhunter** [comment]
After further analysis I came to the conclusion, that `chunkCache.invalidateAll();` doesn't necessarily write anything. Each chunk has a "dirty flag" and doesn't get written unless changed.

However the header always gets written during `force(...)`, which we changed yesterday (see #34). This might also solve this issue.

**Comment by infeo** [comment]
fixed with https://github.com/cryptomator/cryptofs/commit/122cc8eaf69a7407fe366af6126862299f6e3b32
