### ISSUE TITLE
Already existing/opened files throw only generic IOException

### ISSUE THREAD

**Issue by infeo** [cryptomator/cryptofs#45]
CryptoFS version: 1.7.0

When a new or existing file is opend, the CryptoFileSystemImpl.newFileChannel() method is called. In this method is a case distinction between the file is already opened or not. In the latter case, a call is made to the open file handler method `openCryptoFiles.getOrCreate()`
```Java
public OpenCryptoFile getOrCreate(Path ciphertextPath, EffectiveOpenOptions options) throws IOException {
	Path normalizedPath = ciphertextPath.toAbsolutePath().normalize();
	try {
		// ConcurrentHashMap.computeIfAbsent is atomic, "create" is called at most once:
		return openCryptoFiles.computeIfAbsent(normalizedPath, ignored -> create(normalizedPath, options));
	} catch (UncheckedIOException e) {
		throw new IOException("Error opening file: " + normalizedPath, e);
	}
}
```

Every IOException which happens inside the lambda will be wrapped as an UncheckedIOException which is then again wrapped as an normal IOException.

This wrapping leads to an inconsistent behaviour of upper layers, since any more specific IOException is not catched properly.

My suggestion is rather than wrapping the UncheckedIOException we strip it and throw the original exception:

```Java
} catch (UncheckedIOException e) {
	throw e.getCause();
}
```

**Comment by overheadhunter** [comment]
Hmmm... By re-throwing the cause, we preserve the type but discard the full stack trace. But I don't see any other option since [`computeIfAbsent`](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/concurrent/ConcurrentHashMap.html#computeIfAbsent(K,java.util.function.Function)) doesn't support checked exceptions... 🤔

**Comment by overheadhunter** [comment]
No longer relevant in current develop branch, since `getOrCreate` no longer throws any exception. The actual ciphertext file channel will not be created before calling `newFileChannel` on the returned OpenCryptoFile. There are no lambdas involved, hence no wrapping in UncheckedIOExceptions occur:

https://github.com/cryptomator/cryptofs/blob/22913053058540a564fbabfa9999cd490cf6b8d7/src/main/java/org/cryptomator/cryptofs/fh/OpenCryptoFile.java#L50-L73
